[package]
name = "simple-chip8-emu"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
iced = { version = "0.12", features = ["tokio"] }
ratatui = "0.26"
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }